import React from 'react';

const Research = () => (
  <div className = "page-wrapper">
    <h1>Research</h1>
    <p>React router is working correctly</p>
    <button className="btn">Test button</button>
    <button>Test</button>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero ratione ab suscipit atque quae, repudiandae praesentium, amet, dignissimos aut accusantium vel dicta iure qui expedita culpa corporis perferendis error architecto!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, fuga. Velit perspiciatis odio necessitatibus exercitationem repudiandae non ducimus recusandae, facere eius enim rem eligendi praesentium corrupti, ipsa dolorum ab doloribus!</p>
  </div>
);

export default Research;
